# $Header: /home/xubuntu/berlios_backup/github/tmp-cvs/uuu/Repository/toolchain/mkudbfs/Attic/makefile,v 1.2 2003/10/11 12:41:44 bitglue Exp $

mkudbfs: mkudbfs.c mkudbfs.h
	$(CC) -o mkudbfs $(CPPFLAGS) $(CFLAGS) mkudbfs.c

clean:
	rm -f mkudbfs
