#############################################################################
#
#                   Copyright (C) 1996 SciTech Software.
#                           All rights reserved.
#
# Descripton:   Makefile to build the gftcalc program.
#
#############################################################################

CFLAGS += -DTESTING_GTF

gtfcalc$E:  gtfcalc$O

.INCLUDE: "$(SCITECH)/makedefs/common.mk"
