# $Header: /home/xubuntu/berlios_backup/github/tmp-cvs/uuu/Repository/uuu/util/debug/GNUmakefile,v 1.1 2003/12/31 03:22:44 bitglue Exp $

UUUROOT=../..

.PHONY: all clean
all: diable.o

clean: basic-clean
	rm -f *.o

include $(UUUROOT)/Make.config
